pub mod api;
pub mod catalog;
pub mod client;
pub mod daemon;
pub mod history;
pub mod hyprland;
pub mod launch;
mod metrics;
pub mod model;
mod platform;
pub mod protocol;
pub mod resources;
pub mod service;
